SELECT
RECORDIDENTIFIER
, CARRIERID
, ACCOUNTIDGROUPEXTENSIONCODE
, GROUPID
, CARDHOLDERMEMBERID
, ALTERNATEID
, CAREFACILITYID
, PERSONCODE
, CARDHOLDERLASTNAME
, CARDHOLDERFIRSTNAME
, CARDHOLDERMIDDLEINITIAL
, PATIENTLASTNAME
, PATIENTFIRSTNAME
, PATIENTBIRTHDATE AS PATIENTBIRTHDATE_RAW
, CAST(PATIENTBIRTHDATE AS DATE) AS PATIENTBIRTHDATE
, PATIENTSEX
, RELATIONSHIPCODE
, FILLER
, PROVIDERID
, PROVIDERIDQUALIFIER
, PROVIDERNAME
, NETWORKID
, RXNUMBER
, RXNUMBERQUALIFIER
, DATEFILLED AS DATEFILLED_RAW
, CAST(DATEFILLED AS DATE) AS DATEFILLED
, DATEPRESCRIPTIONWRITTEN AS DATEPRESCRIPTIONWRITTEN_RAW
, CAST(DATEPRESCRIPTIONWRITTEN AS DATE) AS DATEPRESCRIPTIONWRITTEN
, RXCLAIMDATEPROCESSED AS RXCLAIMDATEPROCESSED_RAW
, CAST(RXCLAIMDATEPROCESSED AS DATE) AS RXCLAIMDATEPROCESSED
, TRANSACTIONID
, CLAIMSTATUSFLAG
, CLAIMORIGINATIONFLAG
, REIMBURSEMENTTYPE
, NEWREFILLNUMBER
, NUMBEROFREFILLSAUTHORIZED
, PRICESOURCEINDICATOR
, PRODUCTID
, PRODUCTIDQUALIFIER
, DRUGNAME
, DRUGADMINISTRATIONROUTECODE
, GPICODE
, MEDBMEDDINDICATOR
, FILLER2
, GENERICCLASS
, GENERICNAME
, GENERICBRANDINDICATOR
, THERAPEUTICCLASSAHFSCODE
, MULTISINGLESOURCEINDICATOR
, DRUGDOSAGEFORM
, DRUGSTRENGTH
, DEACLASS
, COMPOUNDINDICATOR
, PRODUCTSELECTIONCODEDAW
, OTHERCOVERAGE
, PAYABLEQUANTITY AS PAYABLEQUANTITY_RAW
, dbo.ConvertOverpunch(PAYABLEQUANTITY) / 1000.00 AS PAYABLEQUANTITY
, PHARMACYAMOUNTSUBMITTEDUC
, DAYSSUPPLY AS DAYSSUPPLY_RAW
, CAST(dbo.ConvertOverpunch(DAYSSUPPLY) AS INT) AS DAYSSUPPLY
, SUBMITTEDINGREDIENTCOST
, INGREDIENTCOSTPAYABLE AS INGREDIENTCOSTPAYABLE_RAW
, dbo.ConvertOverpunch(INGREDIENTCOSTPAYABLE) / 100.00 AS INGREDIENTCOSTPAYABLE
, SUBMITTEDDISPENSINGFEE
, DISPENSINGFEEPAYABLE
, SUBMITTEDSALESTAX
, SALESTAXPAYABLE
, SUBMITTEDGROSSAMOUNTDUE
, AMOUNTBILLED
, SUBMITTEDPATIENTPAYAMOUNT
, PATIENTPAYAMOUNT
, FLATCOPAYAMOUNTPAID
, PERCENTCOPAYAMOUNTPAID
, ADMINFEE
, MAINTENANCEDRUGINDICATOR
, FINALPLANCODE
, PLANCODEEXTENSION
, FILLER3
, CARDHOLDERCOPAYDIFFERENTIAL
, FRONTENDDEDUCTIBLEAMOUNT
, AFTERMAXAMOUNT
, TOTALCOPAYAMOUNT
, PATIENTACCUMULATEDDEDUCTIBLEAMOUNT
, DISPENSERTYPE
, AWP AS AWP_RAW
, dbo.ConvertOverpunch(AWP) / 100000.00 AS AWP
, AWPTYPEINDICATOR
, BILLINGREPORTINGCODE
, FORMULARYINDICATORFORMULARYSTATUS
, REJECTCODE1
, PRIORAUTHORIZATIONNUMBER
, PRIORAUTHORIZATIONREASONCODES
, PAMCSCCODEANDNUMBER
, BASISOFCOSTDETERMINATION
, PRESCRIBERNUMBER
, PRESCRIBERIDQUALIFER
, PERFORMANCERXPHARMACYFEEPAID
, PERFORMANCERXFEEPAID
, D0RXNUMBER
, RXNUMBERQUALIFIER2
, ADJUSTMENTREASONCODE
, ADJUSTMENTISSUEID
, RebillIncentive
, VaccineClaimIndicator
, CareNetwork
, CareQualifier
, COBPrimaryPayerAmountPaid
, AppliedHRAAmount
, BILLINGCYCLEENDDATE AS BILLINGCYCLEENDDATE_RAW
, CASE WHEN BILLINGCYCLEENDDATE = 0 THEN CAST('9999-12-31' AS DATE) ELSE CAST(BILLINGCYCLEENDDATE AS DATE) END AS BILLINGCYCLEENDDATE
, MAINTENANCECHOICEINDICATOR
, OPARAmount
, CB5Qualifier
, CB5OTHAmount1
, CB5Qualifier2
, CB5OTHAmount2
, CB5Qualifier3
, CB5OTHAmount3
, PD6ClientTotalOtherAmount
, PD6BuyTotalOtherAmount
, DiagnosisCodeQualifier
, DiagnosisCode
, FILLER4
, MA1.Multi_Source_Code
, MA1.Brand_Name_Code
, MR.Effective_Date
, MR.AWP_Unit_Price
, CASE
WHEN MA1.Multi_Source_Code = 'Y' OR MA1.Brand_Name_Code = 'G' THEN 'G'
ELSE 'B'
END AS BG_Ind

FROM {{ ref('Dummy_Data_dbt_00_Native') }} D

LEFT JOIN {{ source('Lookups','MediSpanA1_Sample') }} MA1 ON D.PRODUCTID = MA1.NDC_UPC_HRI 
AND D.PRODUCTIDQUALIFIER = '03'

LEFT JOIN {{ source('Lookups','MediSpanR_Sample') }} MR ON D.PRODUCTID = MR.NDC_UPC_HRI 
AND D.PRODUCTIDQUALIFIER = '03'
AND D.DATEFILLED >= MR.Effective_Date

LEFT JOIN {{ source('Lookups','MediSpanR_Sample') }} MR2 ON MR.NDC_UPC_HRI = MR2.NDC_UPC_HRI
AND MR.Effective_Date < MR2.Effective_Date
AND D.DATEFILLED >= MR2.Effective_Date

WHERE 
-- Filter out the MedispanR records that are NOT the most recent based on the date filled field
MR2.NDC_UPC_HRI IS NULL

UNION ALL

SELECT
RECORDIDENTIFIER
, CARRIERID
, ACCOUNTIDGROUPEXTENSIONCODE
, GROUPID
, CARDHOLDERMEMBERID
, ALTERNATEID
, CAREFACILITYID
, PERSONCODE
, CARDHOLDERLASTNAME
, CARDHOLDERFIRSTNAME
, CARDHOLDERMIDDLEINITIAL
, PATIENTLASTNAME
, PATIENTFIRSTNAME
, PATIENTBIRTHDATE AS PATIENTBIRTHDATE_RAW
, CAST(PATIENTBIRTHDATE AS DATE) AS PATIENTBIRTHDATE
, PATIENTSEX
, RELATIONSHIPCODE
, FILLER
, PROVIDERID
, PROVIDERIDQUALIFIER
, PROVIDERNAME
, NETWORKID
, RXNUMBER
, RXNUMBERQUALIFIER
, DATEFILLED AS DATEFILLED_RAW
, CAST(DATEFILLED AS DATE) AS DATEFILLED
, DATEPRESCRIPTIONWRITTEN AS DATEPRESCRIPTIONWRITTEN_RAW
, CAST(DATEPRESCRIPTIONWRITTEN AS DATE) AS DATEPRESCRIPTIONWRITTEN
, RXCLAIMDATEPROCESSED AS RXCLAIMDATEPROCESSED_RAW
, CAST(RXCLAIMDATEPROCESSED AS DATE) AS RXCLAIMDATEPROCESSED
, TRANSACTIONID
, CLAIMSTATUSFLAG
, CLAIMORIGINATIONFLAG
, REIMBURSEMENTTYPE
, NEWREFILLNUMBER
, NUMBEROFREFILLSAUTHORIZED
, PRICESOURCEINDICATOR
, PRODUCTID
, PRODUCTIDQUALIFIER
, DRUGNAME
, DRUGADMINISTRATIONROUTECODE
, GPICODE
, MEDBMEDDINDICATOR
, FILLER2
, GENERICCLASS
, GENERICNAME
, GENERICBRANDINDICATOR
, THERAPEUTICCLASSAHFSCODE
, MULTISINGLESOURCEINDICATOR
, DRUGDOSAGEFORM
, DRUGSTRENGTH
, DEACLASS
, COMPOUNDINDICATOR
, PRODUCTSELECTIONCODEDAW
, OTHERCOVERAGE
, PAYABLEQUANTITY AS PAYABLEQUANTITY_RAW
, dbo.ConvertOverpunch(PAYABLEQUANTITY) / 1000.00 AS PAYABLEQUANTITY
, PHARMACYAMOUNTSUBMITTEDUC
, DAYSSUPPLY AS DAYSSUPPLY_RAW
, CAST(dbo.ConvertOverpunch(DAYSSUPPLY) AS INT) AS DAYSSUPPLY
, SUBMITTEDINGREDIENTCOST
, INGREDIENTCOSTPAYABLE AS INGREDIENTCOSTPAYABLE_RAW
, dbo.ConvertOverpunch(INGREDIENTCOSTPAYABLE) / 100.00 AS INGREDIENTCOSTPAYABLE
, SUBMITTEDDISPENSINGFEE
, DISPENSINGFEEPAYABLE
, SUBMITTEDSALESTAX
, SALESTAXPAYABLE
, SUBMITTEDGROSSAMOUNTDUE
, AMOUNTBILLED
, SUBMITTEDPATIENTPAYAMOUNT
, PATIENTPAYAMOUNT
, FLATCOPAYAMOUNTPAID
, PERCENTCOPAYAMOUNTPAID
, ADMINFEE
, MAINTENANCEDRUGINDICATOR
, FINALPLANCODE
, PLANCODEEXTENSION
, FILLER3
, CARDHOLDERCOPAYDIFFERENTIAL
, FRONTENDDEDUCTIBLEAMOUNT
, AFTERMAXAMOUNT
, TOTALCOPAYAMOUNT
, PATIENTACCUMULATEDDEDUCTIBLEAMOUNT
, DISPENSERTYPE
, AWP AS AWP_RAW
, dbo.ConvertOverpunch(AWP) / 100000.00 AS AWP
, AWPTYPEINDICATOR
, BILLINGREPORTINGCODE
, FORMULARYINDICATORFORMULARYSTATUS
, REJECTCODE1
, PRIORAUTHORIZATIONNUMBER
, PRIORAUTHORIZATIONREASONCODES
, PAMCSCCODEANDNUMBER
, BASISOFCOSTDETERMINATION
, PRESCRIBERNUMBER
, PRESCRIBERIDQUALIFER
, PERFORMANCERXPHARMACYFEEPAID
, PERFORMANCERXFEEPAID
, D0RXNUMBER
, RXNUMBERQUALIFIER2
, ADJUSTMENTREASONCODE
, ADJUSTMENTISSUEID
, RebillIncentive
, VaccineClaimIndicator
, CareNetwork
, CareQualifier
, COBPrimaryPayerAmountPaid
, AppliedHRAAmount
, BILLINGCYCLEENDDATE AS BILLINGCYCLEENDDATE_RAW
, CASE WHEN BILLINGCYCLEENDDATE = 0 THEN CAST('9999-12-31' AS DATE) ELSE CAST(BILLINGCYCLEENDDATE AS DATE) END AS BILLINGCYCLEENDDATE
, MAINTENANCECHOICEINDICATOR
, OPARAmount
, CB5Qualifier
, CB5OTHAmount1
, CB5Qualifier2
, CB5OTHAmount2
, CB5Qualifier3
, CB5OTHAmount3
, PD6ClientTotalOtherAmount
, PD6BuyTotalOtherAmount
, DiagnosisCodeQualifier
, DiagnosisCode
, FILLER4
, MA1.Multi_Source_Code
, MA1.Brand_Name_Code
, MR.Effective_Date
, MR.AWP_Unit_Price
, CASE
WHEN MA1.Multi_Source_Code = 'Y' OR MA1.Brand_Name_Code = 'G' THEN 'G'
ELSE 'B'
END AS BG_Ind

FROM {{ ref('Dummy_Data_dbt_01_Native') }} D

LEFT JOIN {{ source('Lookups','MediSpanA1_Sample') }} MA1 ON D.PRODUCTID = MA1.NDC_UPC_HRI 
AND D.PRODUCTIDQUALIFIER = '03'

LEFT JOIN {{ source('Lookups','MediSpanR_Sample') }} MR ON D.PRODUCTID = MR.NDC_UPC_HRI 
AND D.PRODUCTIDQUALIFIER = '03'
AND D.DATEFILLED >= MR.Effective_Date

LEFT JOIN {{ source('Lookups','MediSpanR_Sample') }} MR2 ON MR.NDC_UPC_HRI = MR2.NDC_UPC_HRI
AND MR.Effective_Date < MR2.Effective_Date
AND D.DATEFILLED >= MR2.Effective_Date

WHERE 
-- Filter out the MedispanR records that are NOT the most recent based on the date filled field
MR2.NDC_UPC_HRI IS NULL